DROP SCHEMA IF EXISTS "tours" CASCADE;
DROP SCHEMA IF EXISTS "stakeholders" CASCADE;
DROP SCHEMA IF EXISTS "payments" CASCADE;
DROP SCHEMA IF EXISTS "encounters" CASCADE;
DROP SCHEMA IF EXISTS "blog" CASCADE;
